language: ruby
cache: bundler

rvm:
  - "2.1.2"
  - "2.1.1"
  - "2.1.0"
  - "2.0.0"

script: 'rspec spec/spec_natophone.rb'

branches:
  only:
    - master

notifications:
  email:
    - ericdejonckheere@gmail.com
