language: ruby
cache: bundler

rvm:
  - "2.2.0"
  - "2.1.2"
  - "2.0.0"
  - "1.9.3"

script: 'bundle exec rake spec'

branches:
  only:
    - master

notifications:
  email:
    - ericdejonckheere@gmail.com
